### ISSUE TITLE
add SSL certificate support for postgres

### ISSUE THREAD

**Issue by sknextcode** [frickegroup/wrkflw-engine#100]
We may need to support SSL certificates here as well.

**Comment by alexanderniebuhr** [comment]
I can tackle this, i need to touch the lib anyways

**Comment by alexanderniebuhr** [comment]
@sknextcode should we make this more flexible, by adding support for the whole suite of settings. Or only for the very selective set of options, like adding a trusted `CA`

**Comment by sknextcode** [comment]
> @sknextcode should we make this more flexible, by adding support for the whole suite of settings. Or only for the very selective set of options, like adding a trusted `CA`

I believe it would be good to have this flexibility 👍
